#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import pathlib
import platform
import resource
import shutil
import signal
import subprocess
import tempfile
from typing import Any


def run_curl(
    curl: str, cache: pathlib.Path, *, file_limit: int | None = None
) -> subprocess.CompletedProcess[str]:
    def limit_file_size() -> None:
        if file_limit is None:
            return
        signal.signal(signal.SIGXFSZ, signal.SIG_IGN)
        resource.setrlimit(resource.RLIMIT_FSIZE, (file_limit, file_limit))

    return subprocess.run(
        [
            curl,
            "--max-time",
            "1",
            "--silent",
            "--show-error",
            "--output",
            os.devnull,
            "--hsts",
            str(cache),
            "http://127.0.0.1:1/",
        ],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=10,
        preexec_fn=limit_file_size if file_limit is not None else None,
    )


def curl_version(curl: str) -> str:
    completed = subprocess.run(
        [curl, "--version"],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=10,
    )
    return completed.stdout.splitlines()[0]


def symlink_case(curl: str, root: pathlib.Path) -> dict[str, Any]:
    case = root / "symlink"
    case.mkdir()
    target = case / "target.txt"
    cache = case / "hsts.txt"
    sentinel = b"DO NOT TRUNCATE\n"
    target.write_bytes(sentinel)
    cache.symlink_to(target)

    result = run_curl(curl, cache)
    return {
        "curl_status": result.returncode,
        "curl_stderr": result.stderr.strip(),
        "target_before_bytes": len(sentinel),
        "target_after_bytes": target.stat().st_size,
        "destination_after_type": (
            "symlink"
            if cache.is_symlink()
            else "regular"
            if cache.is_file()
            else "other"
        ),
        "destination_after_bytes": cache.stat().st_size,
        "reproduced": target.stat().st_size != len(sentinel),
    }


def large_hsts(path: pathlib.Path) -> int:
    lines = [
        "# Your HSTS cache. https://curl.se/docs/hsts.html\n",
        "# This file was generated by libcurl! Edit at your own risk.\n",
    ]
    lines.extend(
        f'host{i}.example "29991231 23:59:59"\n' for i in range(300)
    )
    payload = "".join(lines).encode()
    path.write_bytes(payload)
    return len(payload)


def limited_write_case(curl: str, root: pathlib.Path) -> dict[str, Any]:
    case = root / "rlimit"
    case.mkdir()
    cache = case / "hsts.txt"
    before = large_hsts(cache)
    limit = 1024

    result = run_curl(curl, cache, file_limit=limit)
    after = cache.stat().st_size
    return {
        "curl_status": result.returncode,
        "curl_stderr": result.stderr.strip(),
        "file_limit_bytes": limit,
        "cache_before_bytes": before,
        "cache_after_bytes": after,
        "write_error_reported": "write" in result.stderr.lower(),
        "reproduced": after < before,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--curl", default=shutil.which("curl") or "curl")
    parser.add_argument("--output", type=pathlib.Path)
    args = parser.parse_args()

    with tempfile.TemporaryDirectory(prefix="fieldwork-curl-fopen-") as td:
        root = pathlib.Path(td)
        report = {
            "schema_version": 1,
            "experiment": "EXP-20260801-curl-fopen-pretruncate",
            "curl": curl_version(args.curl),
            "platform": platform.platform(),
            "network": "loopback refused connection only",
            "symlink_case": symlink_case(args.curl, root),
            "limited_write_case": limited_write_case(args.curl, root),
        }

    encoded = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(encoded)
    print(encoded, end="")

    return (
        0
        if report["symlink_case"]["reproduced"]
        and report["limited_write_case"]["reproduced"]
        else 1
    )


if __name__ == "__main__":
    raise SystemExit(main())
